#!/usr/bin/env python3
"""把 .claude/skills 同步到所有 Agent Harness 支持的目录（符号链接，保持最新）。

设计
----
- **唯一事实源**：`.claude/skills/`（以及 `.claude/agents/`）。
- 对每个 harness 的项目级 skill 目录建立**符号链接**指向事实源 —— 之后任何
  skill 更新都自动对全部 harness 生效，无需重新拷贝。
- 目标目录由 `scripts/harness-skill-targets.json` 驱动（可扩展）。
  每条标注 `verified`：true = 已在本机用该 harness 的 list/--help 实测确认；
  false = 约定推断，未实测（脚本不会因此失败，只在报告里标注）。
- 额外生成根 `AGENTS.md` 的 **skill 索引**（读取 AGENTS.md 的 harness：
  pi / codex / cursor / opencode / qwen / crush / dsh / hermes 等）。

用法（仓库根）
    python scripts/sync_skills.py                 # 建链接 + 刷新 AGENTS.md 索引
    python scripts/sync_skills.py --check         # 只检查，不写
    python scripts/sync_skills.py --verify        # 额外跑 harness 的 list 命令验证
退出码：有 FAIL → 1；否则 0。
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CONFIG = REPO / "scripts" / "harness-skill-targets.json"
SOURCE = REPO / ".claude" / "skills"
AGENTS_SRC = REPO / ".claude" / "agents"


def load_config() -> dict:
    if CONFIG.exists():
        return json.loads(CONFIG.read_text(encoding="utf-8"))
    return {"targets": [{"harness": "claude", "dir": ".claude/skills",
                         "verified": True, "note": "canonical source"}]}


def link_state(link: Path, src: Path) -> str:
    """→ ok | wrong | dir | missing | file"""
    if not link.exists() and not link.is_symlink():
        return "missing"
    if link.is_symlink():
        try:
            return "ok" if link.resolve() == src.resolve() else "wrong"
        except Exception:  # noqa: BLE001
            return "wrong"
    return "dir" if link.is_dir() else "file"


def make_link(link: Path, src: Path) -> tuple[bool, str]:
    """建目录符号链接；失败回退 junction（Windows）。"""
    link.parent.mkdir(parents=True, exist_ok=True)
    try:
        os.symlink(src, link, target_is_directory=True)
        return True, "symlink"
    except Exception as e:  # noqa: BLE001
        if os.name == "nt":
            r = subprocess.run(["cmd", "/c", "mklink", "/J", str(link), str(src)],
                               capture_output=True, text=True)
            if r.returncode == 0:
                return True, "junction"
            return False, f"{type(e).__name__} / mklink rc={r.returncode}"
        return False, f"{type(e).__name__}: {e}"


def parse_frontmatter(text: str) -> dict:
    """YAML frontmatter parser that handles block scalars (`description: >` / `|`).

    A naive line parser captures only `>` for those skills and leaves the index
    description empty — most knowledgebase-* skills use the block form.
    """
    m = re.match(r"---\s*\n(.*?)\n---", text, re.S)
    if not m:
        return {}
    fm: dict = {}
    key: str | None = None
    buf: list[str] = []
    for ln in m.group(1).splitlines():
        mm = re.match(r"^(\w+):\s*(.*)$", ln)
        if mm:
            if key:
                fm[key] = " ".join(buf).strip()
            key, val = mm.group(1), mm.group(2).strip()
            buf = [] if val in (">", "|", ">-", "|-", ">+", "|+") else [val]
        elif key and ln[:1] in (" ", "\t"):
            buf.append(ln.strip())
    if key:
        fm[key] = " ".join(buf).strip()
    return fm


def skill_index() -> list[dict]:
    out = []
    for d in sorted(SOURCE.iterdir()):
        f = d / "SKILL.md"
        if not (d.is_dir() and f.exists()):
            continue
        fm = parse_frontmatter(f.read_text(encoding="utf-8", errors="replace"))
        desc = re.sub(r"\s+", " ", fm.get("description", "")).strip()
        desc = re.sub(r"^[>|]\s*", "", desc).strip(" >")[:150]
        out.append({"name": fm.get("name") or d.name, "dir": d.name, "desc": desc})
    return out


def write_agents_md(skills: list[dict], targets: list[dict], dry: bool) -> str:
    tgt = ", ".join(sorted({t["dir"] for t in targets}))
    L = ["# AGENTS.md — cross-harness entry point", "",
         "> **Canonical agent instructions live in [`CLAUDE.md`](./CLAUDE.md) — read it first.**",
         "> This file exists so that harnesses which discover `AGENTS.md` (pi, codex, cursor,",
         "> opencode, qwen, crush, dsh, hermes, …) also reach this project's skills.",
         "",
         "## Where the skills live", "",
         f"- **Canonical**: `.claude/skills/<name>/SKILL.md`",
         f"- **Mirrored (symlink → canonical)**: {tgt}",
         "- Regenerate with `python scripts/sync_skills.py`; verify with `python scripts/validate_skills.cjs`.",
         "",
         "## Skill index (generated — do not edit by hand)", "",
         "| skill | what it does | path |", "|---|---|---|"]
    for s in skills:
        L.append(f"| `{s['name']}` | {s['desc']} | `.claude/skills/{s['dir']}/SKILL.md` |")
    L += ["", f"*{len(skills)} skills. Generated by `scripts/sync_skills.py`.*", ""]
    md = "\n".join(L)
    if not dry:
        (REPO / "AGENTS.md").write_text(md, encoding="utf-8")
    return md


def verify_harness() -> list[tuple[str, bool, str]]:
    """跑 harness 自带的 list 命令，确认我们的 skill 被发现。"""
    res = []
    for cmd in (["goose", "skills", "list"], ["gemini", "skills", "list", "--all"]):
        try:
            # harness 多为 node shell 包装脚本 → Windows 下需经 shell 解析
            r = subprocess.run(" ".join(cmd), capture_output=True, text=True,
                               timeout=90, cwd=str(REPO), shell=True)
            out = (r.stdout or "") + (r.stderr or "")
            hit = "knowledgebase-librarian" in out
            res.append((" ".join(cmd), hit,
                        "发现 knowledgebase-librarian" if hit
                        else "未发现（gemini 需先信任该目录：'Skipping project agents due to untrusted folder'）"))
        except Exception as e:  # noqa: BLE001
            res.append((" ".join(cmd), False, f"{type(e).__name__}"))
    return res


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="只检查不写")
    ap.add_argument("--verify", action="store_true", help="额外跑 harness list 验证")
    args = ap.parse_args()

    cfg = load_config()
    targets = cfg.get("targets", [])
    skills = skill_index()

    print(f"[sync] 事实源 {SOURCE.relative_to(REPO)} · {len(skills)} 个 skill · "
          f"{len(targets)} 个目标目录\n")

    rows, fails = [], 0
    for t in targets:
        if not t.get("enabled", True):
            rows.append((t, "skip", "enabled=false（需要时改 true 再跑）"))
            continue
        link = REPO / t["dir"]
        src = SOURCE
        if Path(t["dir"]).resolve() == SOURCE.resolve():
            rows.append((t, "ok", "canonical（无需链接）"))
            continue
        if args.copy:
            # 真实拷贝模式（跨平台/CI 安全：Windows 无开发者模式时符号链接会退化成普通文件）
            if link.is_symlink() or link.is_file():
                link.unlink()
            elif link.is_dir() and any(link.iterdir()):
                shutil.rmtree(link)
            link.parent.mkdir(parents=True, exist_ok=True)
            shutil.copytree(src, link)
            rows.append((t, "ok", "copy（拷贝模式，改动后需重跑）"))
            continue
        st = link_state(link, src)
        if st == "ok":
            rows.append((t, "ok", "符号链接已指向事实源"))
            continue
        if args.check:
            rows.append((t, "warn" if st in ("missing",) else "fail",
                         f"当前状态={st}"))
            fails += 0 if st == "missing" else 1
            continue
        if st == "dir":
            # 已有真实目录：只在为空时替换，避免误删
            if any(link.iterdir()):
                rows.append((t, "fail", "已存在非空真实目录，未覆盖（请人工处理）"))
                fails += 1
                continue
            link.rmdir()
        elif st in ("wrong", "file"):
            link.unlink()
        ok, how = make_link(link, src)
        rows.append((t, "ok" if ok else "fail", how))
        fails += 0 if ok else 1

    md = write_agents_md(skills, [t for t in targets if t.get("enabled", True)],
                         dry=args.check)

    print(f"{'harness':<22}{'dir':<22}{'结果':<8}说明")
    print("-" * 84)
    for t, st, note in rows:
        flag = {"ok": "✓", "warn": "!", "skip": "-"}.get(st, "✗")
        v = "已实测" if t.get("verified") else ("推断" if st != "skip" else "按需")
        print(f"{t['harness']:<22}{t['dir']:<22}{flag} {st:<6}{note}  [{v}]")
    print(f"\n[agents.md] {'(check, 未写)' if args.check else 'AGENTS.md 索引已刷新'} · "
          f"{len(skills)} skills")

    if args.verify and not args.check:
        print("\n[verify] harness 自带发现命令：")
        for cmd, ok, note in verify_harness():
            print(f"  {'✓' if ok else '✗'} {cmd} — {note}")

    print(f"\n[result] {'PASS' if fails == 0 else f'FAIL ({fails})'}")
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main())
